install.packages("ISLR")
library(ISLR)
str(Carseats)
install.packages("C50")
library(C50)
library(rpart)
library(rpart.plot)
tree=C5.0(US ~.,data = Carseats,trials=10)
table(predict(tree,Carseats),Carseats$US)
tree_ms3=rpart(US ~.,Carseats,control = rpart.control(minsplit = 3))
rpart.plot(tree_ms3,main="mainsplit=3")
